---
scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
    basic_auth:
      username: "{{ universe_login }}"
      password: "{{ universe_password }}"

