---
  - name: Update apt Cache
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Wait for APT Lock
    shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

  - name: install dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - apache2-utils
      state: present



